### PR TITLE
Upgrade Travis configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
From https://twitter.com/AndreaBogazzi/status/1345364738407063553

Full-blown CI config :)
https://github.com/szepeviktor/fabric.js/blob/patch-1/.travis.yml 👀

### CODE REVIEW

**Comment by asturur** [comment]
So what are we exactly changing here?
I see we are adding names to step, i m ok with it.
But also we are adding a brach==master clause
What does it do? Will it build PRs too?

**Comment by szepeviktor** [comment]
>  What does it do? Will it build PRs too?

Yes. It will build pushes to master and PR-s directed to master.
https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-builds

**Comment by szepeviktor** [comment]
Bascially
- being explicit in everything
- write config in chronological order

**Comment by asturur** [comment]
i can't get travis to be activated anymore, so i m ditching it for github actions

**Comment by szepeviktor** [comment]
You need to contact their support and ask for free credits.

See mine:
kép

**Comment by asturur** [comment]
i did, it has been 2 weeks now and they have no time to handle it for now.

**Pull request closed without merging**
