### PR TITLE
fix load SVG with the broken image

### PR DESCRIPTION
**Pull request by AlexSergey**
If we try to load SVG with the broken image (ERR_CONNECTION_TIMED_OUT, not 404) it will be error

### CODE REVIEW

**Comment by asturur** [comment]
Images with null element should be possible imho.
What is the output now, can you describe better?

**Comment by AlexSergey** [comment]
If we set null image to fabric.Image it will be error -
http://joxi.ru/D2Pzl65CqJqqlr
I think we need to avoid null images

**Comment by asturur** [comment]
i think we should have a null image definied as an image that can live in fabricJS but with 0 dimensions and that does not throw errors.

Do you have a failing SVG that gives us a failed image?

**Comment by AlexSergey** [comment]
Hmmm... I can't reproduce it from the original fabric.js version. Maybe it happens only our modified fabric.js

**Comment by asturur** [comment]
i remember we fixed it.... but since i said the same thing and i was wrong, i did not say that this time.

**Comment by asturur** [comment]
what is the situation with this bug? can you confirm if the bug exist or not?

**Comment by AlexSergey** [comment]
I investigated this task and I think this happened only my project. We can close it and this won't be merge to fabric.js.

**Pull request closed without merging**
