### PR TITLE
implemented targetHasOneFlip using xor operator

### PR DESCRIPTION
**Pull request by KastriotSalihu**
This function was implemented using  a longer form of expressing an XOR operation. So used the javascript  '^' operator for  XOR.

### CODE REVIEW

**Comment by asturur** [comment]
I looked at this already then i got lost.
I noticed that the XOR operator requires numbers, how is it doing with booleans?

**Comment by KastriotSalihu** [comment]
The XOR operator truth table with booleans would be:
1 1 (0)
1 0 (1)
0 1 (1)
0 0 (0)
Which is the same as what is required from the function.
Perhaps an easier to read approach, would be:
`return target.flipX != target.flipY`
Which again gives the same result.

**Comment by asturur** [comment]
I was referring to the fact the XOR is a bitwise operator and is supposed to be used between numbers and not booleans.
Since  booleanA !== booleanB gives the same result i prefer that a bit more.

**Comment by KastriotSalihu** [comment]
Well since boolean values can be represented as integers (1) and (0), so they would be implicitly converted to integers and be  represented as 32 bit numbers, i.e. 
00000000000000000000000000000001 (1)
00000000000000000000000000000000 (0)
basically
booleanA ^ booleanB 
would be equivalent to
Number(booleanA) ^ Number(boolenB)
where a true-> 1, and false->0
so the XOR operator is being implicitly used between numbers

**Comment by asturur** [comment]
Sure, if you could just use the booleans i would happily merge it.

**Comment by asturur** [comment]
I mean i understand that it will work with implict conversion, i just prefer using the booleans

**Pull request closed without merging**
