### PR TITLE
add code to restore saved clipPath

### PR DESCRIPTION
**Pull request by AlexSergey**
After I saved example 8 from clipPath:
http://fabricjs.com/clippath-part3
"Clipping the canvas"
I tried to restore it from loadFromJSON. But in this method isn't process clip path. I added some code to fix it.

### CODE REVIEW

**Comment by asturur** [comment]
didn't we fix this recently? i remember a pr about this.

**Comment by AlexSergey** [comment]
I found only save fix, where it was replaced from:
data.clipPath = this._toObjectMethod(clipPath, methodName, propertiesToInclude);
to:
data.clipPath = this._toObject(clipPath, methodName, propertiesToInclude);

But restore method is not support clipPath restore to the canvas.

**Comment by asturur** [comment]
great. i ll look at it soon.

**Comment by asturur** [comment]
i want to merge it, but i would like a test too. trying to add it tomorrow since i want to head to a release

**Comment by asturur** [comment]
ok merging it!
i ll add tests in a pr shortly

**Pull request merged**
