### PR TITLE
Passing`propertiesToInclude` to `toObject` to export custom fields fr…

### PR DESCRIPTION
**Pull request by zhangshine**
…om Gradient and Pattern

## Motivation
I want to export custom properties from Gradient and Pattern.

## Changes
Passing `propertiesToInclude` to `toObject`

### CODE REVIEW

**Comment by ShaMan123** [comment]
AFAIK all Gradient/Pattern/Shadow props are exported in `toObject` so I don't see why this is needed.
Are you subclassing any?

**Comment by zhangshine** [comment]
No, we are not subclassing any. We pass additional properties when constructoring a new object, and export these properties. Everything works as normal except Gradient and Pattern.

**Comment by asturur** [comment]
Seems ok to me, we would need a small test and a backport to v6 eventually.
The issue with this approach is that unless for simple properties like `id` or `name` properties that are included in a gradient/pattern may not be included in an object and so causing a bunch of undefined keys on the object side or the Gradient/Pattern side.
With a single argument for the export there isn't much alternative.

**Comment by asturur** [comment]
Please add a test and fix lint.

I also need to think if this is a breaking change.

**Comment by ShaMan123** [comment]
Funny, it is a topic we touched.
The strict approach would be not allowing to assign arbitrary props on an instance and subclassing if in need.
I side this approach but I think this PR is a viable solution as long as we allow non strict assignment of props in the constructor.

**Comment by zhangshine** [comment]
Done. Also removed some duplicated codes.

**Comment by ShaMan123** [comment]
I think v6 should drop the entire concept of `propsToInclude` (and repeating myself, remove default values of course)
`toObject` should do what it does strictly and the dev can subclass, iterate and do what they like.

For v5 this makes sense

**Pull request closed without merging**
