### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by JPAhnen**
As requested in #4507.
This shouldn't be merged yet as it isn't completed yet.

### CODE REVIEW

**Comment by asturur** [comment]
are the jsdoc necessary for the typescript?
i mean if the type script supporting ide, read the inline documentation from the ts file instead of source file.
In this case keeping update 2 copies of docs may be bothersome.

**Comment by JPAhnen** [comment]
I can take them out once the definition is done, but while I'm writing it, it's easier for me leaving it in.

**Comment by PeterBenko** [comment]
FWIW docs don't seem to land in the distributed fabric package (from npm). But naturally, documenting in two places shouldn't be necessary.

**Comment by asturur** [comment]
Docs are on the website, with a small banner.
The banner money are used to print stickers  and ship them.

i did one shipping and no sticker was ever delivered.

**Comment by asturur** [comment]
Is this thing testable in a way that we can be sure it matches fabricJS, what tools are used?

**Comment by asturur** [comment]
would it be possible to move this to a separate repository? like fabricjs/typescript?
Would it be still viable for people to use it from different repo?

I would imagine they would need to install both the typescript definition and the library.

How does typescript normally works? Do file need to be in the same folder as source files?

**Comment by JPAhnen** [comment]
Usually, there are two packages where the definitions should be put: Either the main package itself (i.e. the fabric package), or the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo (where already is a fabric type definition by someone else - but I'm not sure for which fabric version)

**Comment by asturur** [comment]
googled 3 jsdoc to d.ts file converter.
I ll try them soon.

In this way keeping jsdoc updated will be more important and we will get definition for free each release.

**Pull request closed without merging**
