### PR TITLE
perf(): measuring canvas size

### PR DESCRIPTION
**Pull request by ShaMan123**
## Description

The default canvas size is 300 * 150 (weird IMO but nvm)
Measuring doesn't need any pixels so I reduced it to 0 or else it is hust a waste of memory

### CODE REVIEW

**Review by ShaMan123 — COMMENTED** [review]
DONE

**Comment by asturur** [comment]
We can try, i don't think will hurt nothing.
I m not sure the canvas allocate any memory if you don't write or request pixel data from it.
Did you manage to see a reduction of 300x150x4 bytes somewhere? is around 180k of allocation that should disappear somewhere.

**Review by asturur — APPROVED** [review]

**Comment by asturur** [comment]
Also give a look at safari that is the only one that we are not testing in the pipeline, just to be sure

**Comment by ShaMan123** [comment]
safari passed

**Comment by ShaMan123** [comment]
Do we want safari to run in CI? Can it?

**Comment by ShaMan123** [comment]
@asturur it did save 192KB
Screenshot 2024-02-29 at 22 21 12
Screenshot 2024-02-29 at 22 21 55

**Pull request merged**
