### PR TITLE
Fix index issue

### PR DESCRIPTION
**Pull request by Lazauya**
Added a line to make sure I can run the index script. I have no clue what was causing this bug, but for some reason on my machine the `version` function wasn't returning `this`, even though the docs say it should. This change shouldn't change any functionality, only a small bug fix. Specifically, the error was saying: 
```
file:///<redacted>/fabric.js/scripts/index.mjs:490
  .showSuggestionAfterError();
  ^

TypeError: Cannot read properties of undefined (reading 'showSuggestionAfterError')
    at file:///<redacted>/fabric.js/scripts/index.mjs:490:3
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

### CODE REVIEW

**Comment by Lazauya** [comment]
This is a very minor change (1 line, like 8 characters). If @ShaMan123 or @asturur could take a quick glance that'd be great.

**Comment by asturur** [comment]
let me see if i just broke it, because i committed a change to index.mjs just now

**Comment by asturur** [comment]
well ok seems just a chainability issue.
I don't think we should investigate too much, if it fixes for you, shouldn't be a big deal for us.
I wonder if reinstalling with the packagelock i just added would fix anyway.

**Comment by asturur** [comment]
@Lazauya can you run prettier please?
npm run prettier:write

**Comment by Lazauya** [comment]
> npm run prettier:write
@asturur 
Done!

**Comment by ShaMan123** [comment]
> I wonder if reinstalling with the packagelock i just added would fix anyway.

I had too, look at outputs:

```bash
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
```

This is the reason IMO
no need for the PR
@Lazauya please verify

**Comment by ShaMan123** [comment]
try #8779

**Comment by asturur** [comment]
but why the package lock would break commander chainability no the version command?

**Comment by asturur** [comment]
@Lazauya sorry for the back and forth, we updated master again, please try and if it works out of the box close this PR, or we will merge it

**Comment by Lazauya** [comment]
> @Lazauya sorry for the back and forth, we updated master again, please try and if it works out of the box close this PR, or we will merge it

Appologies for the delay. Just tried it and master seems to still be broken.

**Comment by asturur** [comment]
for the sake of understanding, can you tell me exactly what you do and how it breaks?

**Comment by Lazauya** [comment]
> for the sake of understanding, can you tell me exactly what you do and how it breaks?

I tried upgrading everything and doing fresh installs and it seems to work now. Not sure what was happening before, but I'm going to close this I guess.

**Comment by ShaMan123** [comment]
Version inconsistrncy
Npm v3 lock files

**Pull request closed without merging**
