### PR TITLE
Pr/saucelabs

### PR DESCRIPTION
**Pull request by jedateach**
CI build is working smoothly now.

I've configured it to test all the existing node versions, plus PhantomJS and some browsers that came from the ember config, but I would recommend we add more of the available browsers from various platforms: https://saucelabs.com/platforms - especially mobile browsers.

### CODE REVIEW

**Comment by jedateach** [comment]
I did change the credentials before PR, but none of the saucelabs launchers appear to be working - I think there is something up with the authentication. 

Here you can see saucelabs runs are working with my account:
https://travis-ci.org/jedateach/fabric.js/builds/165947729

**Comment by asturur** [comment]
very nice!

**Comment by jedateach** [comment]
I think this is failing because it is a pull request.

This:
https://docs.travis-ci.com/user/sauce-connect/

mentions to set up this:
https://docs.travis-ci.com/user/jwt

**Comment by jedateach** [comment]
Good to go, but I think there is a concurrency limit, I've discussed in #3326

**Comment by asturur** [comment]
we need to do some changes to the test page so that the fixtures have the same relative path as fabricjs.com

**Comment by jedateach** [comment]
OK. Do what you need to.

**Comment by jedateach** [comment]
@asturur Just dropping in to say I haven't forgotten about this. Been rather busy lately.

Is there anything I can do to help this? Is the website code open sourced? Doing so might help to keep the website up-to-date, and make improvements like the one needed here.

**Comment by asturur** [comment]
yes website is on another reposotory. i did additional cleaning of tests. i ll try to recap what is missing

**Pull request closed without merging**
