### PR TITLE
Update build.js

### PR DESCRIPTION
**Pull request by neopheus**
Add alignment and centering to build.js

### CODE REVIEW

**Comment by asturur** [comment]
Those are not official features, and are not fully functional i think. I do not want to have them in the build or i have to support them also.

**Comment by neopheus** [comment]
I understand. It's just to be able to create a build with these elements easily

**Comment by asturur** [comment]
we may work on it, maybe on the website.
I think align guideline and centering are not in good state now, let's move this later in time

**Comment by asturur** [comment]
i need to get 2.0 out in decent condition. I cannot add more things to it before release.

**Comment by neopheus** [comment]
no problem ;)

**Pull request closed without merging**
