### PR TITLE
ci(): Revert "invoke tests after changelog action (#8974)"

### PR DESCRIPTION
**Pull request by ShaMan123**
This reverts commit d5a955325a5ad9a521cd2b5831a768776dbddbf2.

## Motivation

It was supposed to make CI trigger after the changelog action but github is smarter than that, at least we can trust github (if not TS).
So I will close and reopen a PR to make the test UI visible

### CODE REVIEW

**Review by asturur — DISMISSED** [review]
At some point we will want to cancel older actions i a new commit comes in quickly and this will hit us on the teeth.

**Comment by ShaMan123** [comment]
You mean cancel the previous run if it is still running?

**Comment by asturur** [comment]
yes

**Review by asturur — DISMISSED** [review]

**Review by asturur — APPROVED** [review]

**Comment by asturur** [comment]
If you are done with this you can merge. I m not sure you are done or you are still elaborating

**Pull request merged**
