### PR TITLE
fix: when style doesn't have anything to match, parser failed

### PR DESCRIPTION
**Pull request by k88manish**
I faced this issue recently when I used and SVG which had only google font imported in that case it failed to parse the style content and was not able to proceed any further.

### CODE REVIEW

**Comment by asturur** [comment]
And does that SVG works in the browser today? what spec is that?

**Comment by k88manish** [comment]
> And does that SVG works in the browser today? what spec is that?

This is trimmed down version of large SVG which got me this exception. But if you need the complete SVG file let me know

**Comment by asturur** [comment]
my question is:
i can't find the import spec for svg in `www.w3.org`.
What kind of SVG is it? is it standard? Does it render in browser?

**Comment by k88manish** [comment]
> 

Yes this SVG works in browser. 
I will try to find the spec but to be honest I am not very familiar with SVG specs

**Comment by asturur** [comment]
Handling the @import statement inside svg should be the correct solution, but that may be hard. this solution could be backported on the current codebase

**Comment by asturur** [comment]
I wanted to make the PR from your branch but is not possible

**Comment by asturur** [comment]
@k88manish thank you for this fix and pr.
It has been merged as #9602

**Pull request closed without merging**
