### PR TITLE
feat: improve _fireSelectionEvents performance

### PR DESCRIPTION
**Pull request by proke03**
## Motivation
#8588 

## Changes
Reduce two forEach to one for

### CODE REVIEW

**Comment by ShaMan123** [comment]
@proke03 thanks for PRing
However, I am not sure the change is worth the trouble. Does it optimize performance? You need to prove it.
Because it makes the code less readable IMO it must have a gain.
The only case this PR has an impact is if oldObjects and objects have many shared objects (then the code loops almost half of what it loops currently), which doesn't really happen in any case.
I would try a different approach if this is a pressing matter, or prove me wrong.

**Comment by proke03** [comment]
Thank you for your review. I think you're right.
By the way, there is an error in the part that I did not modify. Do you know the cause? It seems to be the cause of the build failure.

캡처_2023_04_05_13_10_19_804

**Comment by ShaMan123** [comment]
> By the way, there is an error in the part that I did not modify. Do you know the cause? It seems to be the cause of the build failure.

#8756

**Comment by proke03** [comment]
Thank you!

**Pull request closed without merging**
