### PR TITLE
ci() Try nicer names for GHA

### PR DESCRIPTION
**Pull request by asturur**
Recent refactor of tests create GHA with names i have difficulties discerning between one and the other.

### CODE REVIEW

**Comment by asturur** [comment]
@ShaMan123 for me those are more clearly identifiable.
The slash between the main title and the subtitle is not removable sadly.
That alone would be worth 6 independent files.

**Review by ShaMan123 — APPROVED** [review]
What emoji shall we use for `PR Quality Check`?

**Comment by ShaMan123** [comment]
🚧?

**Comment by ShaMan123** [comment]
🩺
🛠️
🔨
🎛️
🌡️

**Review by ShaMan123 — APPROVED** [review]

**Comment by asturur** [comment]
image

i tried this before, but on my screen is so tiny seem like an hair more than an emoji

**Comment by asturur** [comment]
the crossed hammer for the build is good enough, we can update it later.

**Pull request merged**
