### PR TITLE
ci(): add `build.lock`

### PR DESCRIPTION
**Pull request by ShaMan123**
This PR adds a lock file to the repo when build is in progress.
Then tests listen to the lock file to wait for the build to complete and avoid running during the build.

So now we can run tests without checking if build finished. I got frustrated from that.

## Changes
- extracted build logic to  `scripts/build.mjs`
- `scripts/buildLock.mjs` - lock logic
- `scripts/buildReporter.mjs` - called by build script

## Next Up
- I want to extract logic from `scripts/index.js` to modules in a dedicated PR so it becomes readable
- I will use this in the sandbox PR #8135  instead of running rollup API

### CODE REVIEW

**Review by ShaMan123 — COMMENTED** [review]
READY

**Review by ShaMan123 — COMMENTED** [review]
Refactored to use the rollup cli hooks as they are more reliable
READY

**Comment by asturur** [comment]
What is wrong with the rollup api?
This CI is growing in complexity non stop.

**Comment by asturur** [comment]
I read somewhere you were asking to install a certain app to the repo, related to codesandbox.
I checked in settings but the only installed app is the stale bot.
Where did you try to add it?

**Comment by ShaMan123** [comment]
> This CI is growing in complexity non stop.

complex CI means easy DX

https://user-images.githubusercontent.com/34343793/190955030-dbbb78c0-a75a-4bae-aa9e-fe6ef370bf71.mp4


The rollup API is fine.
The need for a build lock is for testing.
It is annoying and pointless switching tabs to see when the build finished. 
In #8172 I had to use something to inform the sandbox to refresh so I used the rollup API but with the lock file it is much simpler.

**Comment by ShaMan123** [comment]
I wanted to add the codesandbox ci app for #8135 
I tried throw links redirecting me to github from codesandbox but I don't think I have permissions.

**Comment by asturur** [comment]
oh so give me those links i can add it, probably is an admin thing only

**Comment by asturur** [comment]
add changelog i ll merge it afterward

**Review by asturur — APPROVED** [review]

**Review by asturur — APPROVED** [review]

**Comment by ShaMan123** [comment]
@asturur https://github.com/apps/codesandbox-ci

**Comment by ShaMan123** [comment]
see #8135 for links and details

**Pull request merged**
