### PR TITLE
Fix TypeError: fill.render is not a function

### PR DESCRIPTION
**Pull request by chr314**
check if fill.render is function

fixing https://github.com/fabricjs/fabric.js/issues/7171#issuecomment-876153693

### CODE REVIEW

**Comment by asturur** [comment]
@ShaMan123 does this seems a legit fix for you?

**Comment by ShaMan123** [comment]
Yes and no.
Yes it will fix the error but I am not sure why it is happening. 
The logic assumes that the background/overlay color has been replaced by a `Rect` so it could be erased by the eraser. 
That is where the true bug originates from.
I think I can reproduce now that I understand.

When I built the eraser mixin this specific logic was handled by the eraser but later on I moved it to Canvas.

If I am not mistaken this is where the bug comes from:
https://github.com/fabricjs/fabric.js/blob/e6d16d3a03b972cf63babb59b351916d007fa563/src/mixins/eraser_brush.mixin.js#L77
https://github.com/fabricjs/fabric.js/blob/e6d16d3a03b972cf63babb59b351916d007fa563/src/mixins/eraser_brush.mixin.js#L95

This logic was correct when the eraser brush was in charge of replacing bg/overlay color to rects if they were erasable.
Now if fails because it has no replacement mechanism.
I moved it because it seemed too expensive to run every mouse move and I stick to it.

So if my assumptions are correct the true fix would be to change the else blocks and add rects instead of filters/string values.
In addition, this proposed fix will only remove the error but it will not render the actual bg/overlay.

**Therefore I think this is not a fix after all.**

There is another bug regarding this block of code that I pushed into #7100:
The bg/overlay color should not be affected by canvas transform.

**Comment by ShaMan123** [comment]
@chr314 Could you help me reproduce?
Did you load the canvavs from JSON/SVG before this error happened?

**Comment by ShaMan123** [comment]
I can't reproduce.
@chr314 are you setting bg/overlay color directly (assigning) or using the `setBackgroundColor` method as **STATED** in the instructions of the demo??

look at these 2 repos:
https://codesandbox.io/s/d16uq
https://codesandbox.io/s/dl79j

Read their comments to understand what they check

**Comment by ShaMan123** [comment]
> Yes and no.
> Yes it will fix the error but I am not sure why it is happening.
> The logic assumes that the background/overlay color has been replaced by a `Rect` so it could be erased by the eraser.
> That is where the true bug originates from.
> I think I can reproduce now that I understand.
> 
> When I built the eraser mixin this specific logic was handled by the eraser but later on I moved it to Canvas.
> This logic was correct when the eraser brush was in charge of replacing bg/overlay color to rects if they were erasable because it checked it every render.
> Now it fails because it has no replacement mechanism.
> I moved it because it seemed too expensive to run every mouse move and I stick to it.
> 
> If I am not mistaken this is where the bug comes from:
> https://github.com/fabricjs/fabric.js/blob/e6d16d3a03b972cf63babb59b351916d007fa563/src/mixins/eraser_brush.mixin.js#L77
> 
> 
> https://github.com/fabricjs/fabric.js/blob/e6d16d3a03b972cf63babb59b351916d007fa563/src/mixins/eraser_brush.mixin.js#L95
> 
> So if my assumptions are correct the true fix would be to change the else blocks and add rects instead of filters/string values.
> In addition, this proposed fix will only remove the error but it will not render the actual bg/overlay.
> 
> **Therefore I think this is not a fix after all.**
> 
> There is another bug regarding this block of code that I pushed into #7100 (which is waiting for your feedback):
> The bg/overlay color should not be affected by canvas transform.

After looking closely at serialization I can say confindently that the eraser mixin works as expected with no problems since serialization calls `setBackgroundColor` or `setOverlayColor` that the eraser mixin extends.

https://github.com/fabricjs/fabric.js/blob/2eabc92a3221dd628576b1bb029a5dc1156bdc06/src/mixins/canvas_serialization.mixin.js#L142

**Comment by ShaMan123** [comment]
What I would do is add a warning here instead explaining how to set `bg/overlay` color when using eraser and referencing the docs

**Comment by chr314** [comment]
@ShaMan123  thanks
yeah I think I was using the bg color the wrong way

**Pull request closed without merging**
