### PR TITLE
chore(TS) remove controls from prototype

### PR DESCRIPTION
**Pull request by asturur**
## Motivation

Controls are the last part of the data we have on the protoype.
This pr removes them and put them in the defaults.
Controls are still shared between instances because of javascript mutability of objects.

### CODE REVIEW

**Comment by asturur** [comment]
@ShaMan123 probably we can go up to having a different control object per instance, since a way to rollback with few lines of code is still possible ( if the developer desire so ).

**Review by ShaMan123 — APPROVED** [review]
Great.
I didn't expect this pivot from you.

**Comment by asturur** [comment]
> Great. I didn't expect this pivot from you.

I want simple code and options.
I don't want to maintain a project that is more complicated than an hobby, it adds too much friction on working on it when i should be doing fun things.

**Comment by ShaMan123** [comment]
I want to add that logic that was adapted to shared controls (e.g. control visibility, passing down the object that uses the control etc.) might be thought of as obsolete.
I am leaving this comment to point out that in terms of scoping we can attach the object ref to a control and scope visibility to the control and not to the object. Same goes for coords.
Then doing something like `object.control.br.isVisible()`, `object.control.br.containsPoint()` is easy

**Comment by ShaMan123** [comment]
And we can make the controls object a class holding more methods such as setting visibility

**Pull request merged**
