### PR TITLE
fix(EraserBrush): inverted erasing

### LINKED ISSUE #7688: EraserBrush: `inverted` + object stacking is wrong
## Version
5.0.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?

## Steps To Reproduce

1. create erasable and non erasable objects
2. erase
2. put them one on top of the other
4. switch to inverted erasing
5. erase

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```
</p></details>

## Expected Behavior
respect object stacking

## Actual Behavior
renders over non erasable objects regardless of object stacking

## fix
If I change logic to mimic the non inverted I think it will fix

### PR DESCRIPTION
**Pull request by ShaMan123**
closes #7688 
https://codesandbox.io/s/49qcgd

@asturur please merge this now for v5

### CODE REVIEW

**Comment by ShaMan123** [comment]
ready to merge

**Comment by ShaMan123** [comment]
@asturur this one as well

**Comment by ShaMan123** [comment]
ready

**Comment by ShaMan123** [comment]
## Before
before

## After
after

**Comment by ShaMan123** [comment]
approve me please!

**Review by asturur — APPROVED** [review]

**Pull request merged**
