### PR TITLE
fix(IText): `exitEditing` should clear contextTop

### PR DESCRIPTION
**Pull request by ShaMan123**
## Description

Reproduce:
- select text
- deselect text by pressing the canvas

Expected selection to be cleared.
It doesn't
This is a regression caused IMO by making `abortCursorAnimation` effecient.
We need to think about this.
I am not sure if there are more cases we want to clear selection.
The only path that I am not sure about is this:

https://github.com/fabricjs/fabric.js/blob/00bbc7ce2081d37c273fcdf4804ea2459fc2736b/src/shapes/IText/ITextKeyBehavior.ts#L106-L108

The rest seem fine.
I am quite sure that draggable text needs blur NOT to clear selection, but that might be incorrect. Due to `_renderDragEffects` handling that.

### CODE REVIEW

**Comment by asturur** [comment]
> This is a regression caused IMO by making `abortCursorAnimation` effecient.

you mean making `abortCursorAnimation` broken.
Those are just points to my stance, don't touch.

**Review by asturur — DISMISSED** [review]

**Review by asturur — APPROVED** [review]

**Comment by asturur** [comment]
Are you verified since you enabled controller on textbox that when text-selection is active, scaling down the textbox works correctly and doesn't leave behind a trail of uncleaned selection?

**Review by asturur — APPROVED** [review]

**Comment by ShaMan123** [comment]
> Are you verified since you enabled controller on textbox that when text-selection is active, scaling down the textbox works correctly and doesn't leave behind a trail of uncleaned selection?

You mean this?


https://github.com/fabricjs/fabric.js/assets/34343793/9d9b5155-d675-4cc0-87a8-429a05636c06

**Comment by asturur** [comment]
yes because we are clearing up the top layer only on the texbox area, i m not sure if that means sometimes the 2 sizes aren't in sync. 

I would expect it maybe as an edge case while shrinking equally from the BR quicky

**Comment by ShaMan123** [comment]
These are the paths which call clearContextTop:
- `_renderDragEffects`, `dragEndHandler`: drag effects clear context top and are tested I think
- `abortCursorAnimation`
- `onKeyDown` if navigating with arrows etc.
- `_exitEditing`
- `renderCursorOrSelection`: this is the case you are referring to, right?

I am not sure how it is handled but take notice that in the video I resized using `set`, which is how the resize control does it and since that worked as expected I think we are good.
I checked the stack trace and indeed it is handled by `renderCursorOrSelection` called from `render`.
I think I worked on this before but I can't recall how it works correctly if the size changes.
But it does

**Pull request merged**
