### PR TITLE
fix setDimensions css unit

### PR DESCRIPTION
**Pull request by Julyyq**
When invoke `setDimensions` method with using options `{cssOnly: true}`, the `cssValue` variable is not added postfix "px" unit, so the`cssOnly: true` option is not working.

### CODE REVIEW

**Comment by kangax** [comment]
Don't understand the issue here

**Comment by Julyyq** [comment]
@kangax See the following code snippet:

    if (!options.cssOnly) {
      this._setBackstoreDimension(prop, dimensions[prop]);
      cssValue += 'px';
    }
    if (!options.backstoreOnly) {
      this._setCssDimension(prop, cssValue);
    }

If set `cssOnly: true`, the line code `cssValue += 'px';` will not be called, and the `this._setCssDimension(prop, cssValue);` method pass the cssValue variable without unit "px".

**Comment by kangax** [comment]
Strange, how did it even work before? I remember people saying that it works (I personally haven't used it)

**Comment by kangax** [comment]
Also, a test would be nice for this!

**Comment by Julyyq** [comment]
@kangax Unit test-case is done, definitely it's a bug so I don't open a new branch for pull request. Hope it doesn't matter.

**Comment by inssein** [comment]
@Julyyq there may be an invalid assumption on what that does. Check out the tests that are broken because of the change.

**Comment by Julyyq** [comment]
@inssein I clone the master branch without any code modifications, run `npm test`, and occurs several errors. It's not about my changes.

**Comment by sapics** [comment]
@Julyyq check travis ci result in https://travis-ci.org/kangax/fabric.js/builds/67474320.

**Comment by Julyyq** [comment]
@sapics Thank you, 100% becomes 100%px.

**Comment by Julyyq** [comment]
@kangax `cssOnly: true` worked before only for percentage values like 100%, and test case only tests percentage cases. Now it only supports "px" within my fix, without "%" or "em".  But I saw `Sets dimensions (width, height) of this canvas instance. when options.cssOnly flag active you should also supply the unit of measure (px/%/em)` in the api document. How to handle this? Should only support "px" or make some extra coding to support "em" and "%"?

**Comment by asturur** [comment]
Before writing additional code, check if the function "parseUnit" that i think is in fabric.util, is ok for the purpouse.

**Pull request closed without merging**
