### PR TITLE
took parser from svgo package

### PR DESCRIPTION
**Pull request by shahafan**
Took path parser from https://github.com/svg/svgo/blob/master/plugins/_path.js

### CODE REVIEW

**Comment by asturur** [comment]
Can i ask what is the goal here?

We are picking up other people's code without proper attribution.
Is not es5 compatible and uglifyJS will probably fail.
We are swapping 32 lines of code with 68.

What made you change the code?
Is there something our current path parser cannot parse?
Is this code sensibly faster?

**Comment by shahafan** [comment]
The current parser isn't compatible with the svg standards, it's just looking for spaces / commas.
On elliptical arc you don't have to include spaces and the parser won't draw the right paths.

Any svg that will get optimization with svgo will fail.

We've started to use this parser now and this has solves us tons of breaks.

I can rewrite their code to be es5 compatible and also try to make it shortener..

If you want an example you can try this one:

https://static.wixstatic.com/shapes/db42c0_af158af3367e4dc9bee9fe009507285d.svg

Let me know if you want me to do here anything else.

**Comment by asturur** [comment]
Those are valuable informations. Thanks for clarifying.
I would like if is possible for you to open a PR with one change at time.
SVGO will compress the path value, using specs, and something will fail.
We should take one of those failing paths and update our code to handle it, without switching to SVGO parser entirely.
That SVG path you provided is good.
We also need tests.

**Comment by shahafan** [comment]
I'll do my best to find the time.

**Comment by gloriousjob** [comment]
@shahafan My PR got pulled into 4.2.0. Would that resolve this PR?

**Comment by asturur** [comment]
yes this can be close

**Pull request closed without merging**
