### PR TITLE
feat: Add CommonJS export method support to HEADER.js

### PR DESCRIPTION
**Pull request by junghwan-park**
refer: fabricjs/fabric.js#5822

### CODE REVIEW

**Comment by asturur** [comment]
I'm not opposed to this, but i need to understand some things firsts.

Why the default and name import is necessary? i would prefer to have one only.
In your issue you refer to `import fabric from 'fabric'` why can't you change that to `import { fabric } from 'fabric';`

**Comment by junghwan-park** [comment]
@asturur 
As I issued earlier in #5822, I've encounter the module importing problem in difference of module exporting depth.
I issued #5823 yesterday, but I resolved karma test issue via karma and webpack configuration today. I've mis-configured karma & webpack config file yesterday.  :(

Anyway, Here is my thought. CommonJS module definition depth is one step deeper from others.

**three way to get `fabric` module**
- In Web Browser : using `fabric` direct
```js
fabric.util.createClass();
```
- In AMD module : using `fabric` direct
```js
define(['fabric'] , function (fabric) {
    return function () {
        fabric.util.createClass();
    };
});
```
- In CommonJS module : `( { fabric: { /* genuine */ } } )`
```js
require('fabric').fabric.util.createClass();
```

It might have bring some confusing situation to someone as I experienced. 

If you think this is not needed right now, just close PR.

Thanks :)

**Comment by iongion** [comment]
Could this be solving the problems caused by attempting to use fabric as external in webpack  ?.

Now, if I try to make it an external and load it from CDNJS , the imported object will be empty with babel import statements like:

```javascript
import { fabric } from 'fabric;
```

**Comment by asturur** [comment]
what do you mean by 'an external'?

**Comment by iongion** [comment]
@asturur sorry, I mean this:

https://webpack.js.org/configuration/externals/

In my case I use the CDN of CDNJS

https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.4.0/fabric.js

And the index.html looks like this

image

Allowing people not to bundle the entire fabric library in a large vendors file.

**Comment by asturur** [comment]
i m not sure what  is wrong in having a vendor file as large as you need.
i would like to solve as many as possible import issues anyway.

the one for which the pr has been open is still a bit unclear to me

**Comment by hga77** [comment]
I think I am having the same issue... Look here
https://github.com/fabricjs/fabric.js/issues/6552

**Pull request closed without merging**
