### PR TITLE
Update canvas.class.js

### PR DESCRIPTION
**Pull request by ShaMan123**
change check from group to collection

### CODE REVIEW

**Comment by asturur** [comment]
is this a bugfix? what is actually changing?

**Comment by ShaMan123** [comment]
This changes makes any collection of objects support nested selection.
All it needs is `subTargetCheck = true` and `_objects`

I opened these PRs because I didn't want to commit to v6!, not to disturb your reviewing process

**Comment by ShaMan123** [comment]
This is what can be achieved from the change
https://github.com/fabricjs/fabric.js/pull/7669#issuecomment-1067121710

**Comment by ShaMan123** [comment]
Handled by #7744

**Pull request merged**
