### PR TITLE
Fix multiple applications of blend image filter with transparent images

### PR DESCRIPTION
**Pull request by brandondong**
Repro case: https://jsfiddle.net/ojt42731/94/

### CODE REVIEW

**Comment by asturur** [comment]
the change looks good.
Would you mind adding a small visual test for it? We have a filter test for resizing and adding a test for blend image should be straight forward

**Comment by brandondong** [comment]
No idea why the tests are failing. Passing locally for me.

**Comment by asturur** [comment]
i ll check them

**Comment by asturur** [comment]
i think i ll merge as it is and fix locally since is easier. We need a more colorfull image if we want to make a test, if is very faint is harder to see visually what is going wrong.

**Pull request merged**
