### PR TITLE
minor empty check fix in getCSSRules

### PR DESCRIPTION
**Pull request by ijaz-saeed**
files with following style tags are not processed, needs this empty or undefined check. 

 **<style type="text/css">@import url ...**

### CODE REVIEW

**Comment by asturur** [comment]
Can you tell me more about those style tags?
Can you reference me some kind of spec, i never seen those.

**Comment by asturur** [comment]
PR looks fine.

**Comment by ijaz-saeed** [comment]
> Can you tell me more about those style tags? Can you reference me some kind of spec, i never seen those.

just noticed , the similar issue is reported by someone else , https://github.com/fabricjs/fabric.js/pull/7434

**Comment by asturur** [comment]
closing this since we changed the parser and there are no regex anymore.

**Pull request closed without merging**
