### PR TITLE
fix(IText): key maps

### PR DESCRIPTION
**Pull request by ShaMan123**
## Motivation
https://github.com/fabricjs/fabric.js/discussions/8419#discussioncomment-4201286

## Description

Wrongly migrated properties

### CODE REVIEW

**Comment by ShaMan123** [comment]
> **Build Stats**
> 
> file / KB (diff)	bundled	minified
> fabric	1061.814 (**+1.733**)	313.087 (**+0.515**)

I find it hard to believe the stats are correct

**Comment by ShaMan123** [comment]
ready

**Review by ShaMan123 — COMMENTED** [review]
added a test

**Comment by asturur** [comment]
@ShaMan123 i refactored it to be its own const, little bit typed and kept on the default values, otherwise was copied every instance and not modificable as a whole.

**Comment by asturur** [comment]
> > **Build Stats**
> > file / KB (diff)	bundled	minified
> > fabric	1061.814 (**+1.733**)	313.087 (**+0.515**)
> 
> I find it hard to believe the stats are correct

I think the stats are correct, before as a type it would disappear, while now it stays in the code, so that's normal i think.

**Comment by ShaMan123** [comment]
OK
#7865 will change this again I believe, but doesn't have to.
Let's merge

**Pull request merged**
