### PR TITLE
ci(): install prettier

### PR DESCRIPTION
**Pull request by asturur**
This PR adds Prettier and the commands to use it, but do not actually format any code.
Actual code formatting can be discussed, i have no strong optinions apart the 2 i wrote in the configuration file.

### CODE REVIEW

**Comment by asturur** [comment]
To me the stupid vscode doesn't work.
Only from npm command

**Comment by asturur** [comment]
image

ok it was this setting here

**Comment by ShaMan123** [comment]
I think you should commit the `.vscode` folder and then the config will be set locally no matter what

**Comment by asturur** [comment]
will follow PR that formats all src folder.

**Comment by asturur** [comment]
> I think you should commit the `.vscode` folder (if existing) and then the config will be set locally no matter what

that will force everyone to have the same options? with overlaps?
We could have an example file for vscode anyway.

We can enforce linting with a push or commit hoot

**Comment by ShaMan123** [comment]
I think it will

**Comment by ShaMan123** [comment]
https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings

**Comment by ShaMan123** [comment]
#8281

**Pull request merged**
