### PR TITLE
Allow cutted words in a Textbox shape

### LINKED ISSUE #2376: Entering text in a Textbox object expands it when there aren't newlines
I've created a `Textbox` object with width `400px`  

When entering text that doesn't have any newlines, it expands the `Textbox` beyond `400px`  

Not sure if this is intended behaviour  
If it is, would be great to be able to pass in a property to preserve the width and force the text to a newline

### PR DESCRIPTION
**Pull request by JSteunou**
It's a way to mimic html/css world *white-space normal or pre-wrap* property, because sometime you want the text to fit exactly in the `width` you set no matter what.

Example here http://jsfiddle.net/Da7SP/736/ one with `minWidth` one without, both with the option activated and a last one without it.

this would close #2376

### CODE REVIEW

**Comment by asturur** [comment]
oh this has an open issue around the tracker.
With a similar implementation that i provided some time ago ( before text rewrite so no more usable ).

This has to wait 2.0 release we can discuss it meantime to see perf issue/testing/ problem that may arise.

**Comment by JSteunou** [comment]
Perf are not bad, it's just like having more tiny words. Like the other PR I will need guidance for testing.

I found these related issue  #2376 & #4000

**Comment by lsiann** [comment]
The last letter of a cutted word can not be selected.Maybe need a fix somewhere else

**Comment by sentoro** [comment]
Does anyone going to fix this issue? the text wrap still not working for me in 2.0

**Comment by asturur** [comment]
What is to be fixed actually?

**Comment by blobinabottle** [comment]
hey @asturur any idea why the bug mentioned? The graphemeLines returned by _wrapLine seems correct. Where would you look to try to fix it?

I know it's not in your roadmap, but this functionality could help us a lot :-)

**Comment by asturur** [comment]
We can revisit it. I do not remember.
I wonder if it makes sense to break works in this way, without a breaking sign in the middle.

**Comment by blobinabottle** [comment]
The use for us is more about using asian language (without spaces apparently) in textbox and being able to resize them. For the moment it's impossible (because considered as a long non-breaking word).

**Comment by asturur** [comment]
Apparently.
Maybe they use other dividers, while fabricjs split just with space, like an illitterate barbarian.
That is something to fix anyway, if we did not do already, including the other 2 or 3 unicode spaces that are out there.

**Comment by blobinabottle** [comment]
http://www.fileformat.info/info/unicode/category/Zs/list.htm I guess this is an helping list. I see U+3000 as ideographic space

**Comment by blobinabottle** [comment]
But this seems way more complicated as Japanese doesn't have space at all. There are libraries to detect words:
https://stackoverflow.com/questions/49367783/js-split-for-japanese-string

After trying in several softwares they just consider Japanese as a big long word:
https://cl.ly/e2600c23a296 (result in Illustrator, ideally it should be segmented as two "words"  '公開' and '文書' )

So I think the approach of this PR is probably the easiest. It's working whatever the language you're using.

**Comment by asturur** [comment]
what we can do is making the splitWords function a part of fabric.util as much as grapheme split so that devs can override it when they need to support other languages.

**Comment by asturur** [comment]
Is also still unclear if the wordbreaking should trigger just for words longer than width or always to fill up spaces. I can foresee people coming with good reasons for the opposite feature we will choose.

**Comment by blobinabottle** [comment]
That doesn't make sense. If you try any other softwares it behave as this PR... 
And you can still use the option allowCuttedWords for the ones unhappy about it. No?

**Comment by asturur** [comment]
i think you misunderstood me.
Should you split each word that is bigger than width, or split each word to fit width, when the option is active?

**Comment by blobinabottle** [comment]
Ah but then that's something else; "hyphenation" I think. And I guess you could only make it for English (or languages where you know how to cut words). 
But you can only find this options in "advanced" softwares (illustrator, indesign, photoshop). Sketch Figma and Framer are doing as this PR and they have no option about hyphenation.

**Comment by blobinabottle** [comment]
Google Slides and keynote are doing the same (no hyphenation): breaking word longer than the desired width.

**Comment by blobinabottle** [comment]
What I can tell is that this PR is working pretty well with styles.
toSVG is perfect as well. 

Only issues I saw:
- cursor and selection position (we have 1 extra char calculated by line created by cutted word)
- if you resize big texttblock (font size > 40px) to a veiry small width, cutting word will stop working.

I can offer to beta-test this PR as much as possible  (if this can help you :-D)

**Comment by asturur** [comment]
well i want to merge clippath first, and give a way a new render method for
higher res. I also need interaction tests in general.

Publishing features on top of features and leaving bugs open is frustrating
for me and for library user in general.

**Comment by asturur** [comment]
I do not remember now, i need to read on the computer. I do remember that measuring text in order to split it, instead of after splitting it, was a problem.

I ll be back in the evening and try to point you in some direction

**Comment by JSteunou** [comment]
FYI I'm not a big fan of how I did this. It should have been written as a recursive functional code, but the old code is imperative so I kept imperative code. But for cases like this one, imperative is not easy to read.

**Comment by asturur** [comment]
you should propose better code if you have it. readibility can be addressed with comments.

I care it works, i remember my first patch could split a long word in many lines.

**Pull request closed without merging**
