### PR TITLE
fixed renderControls order

### PR DESCRIPTION
**Pull request by DaxGama**
Fixed controls render order for ActiveSelection

**Before**
Child controls renders over ActiveSelection
image

**After**
ActiveSelection controls renders over child's
image

This is my first contribution to this project, please let me know if I have missed out anything.

### CODE REVIEW

**Comment by asturur** [comment]
ok so the borders, no the controls.
In that case this could make sense. I need to think carefully with nested selections, but with active selection that is never the case.

**Comment by asturur** [comment]
this should be ok. If it turns out it isn't i ll have to revert.

**Comment by niketaOptimumnbrew** [comment]
> this should be ok. If it turns out it isn't i ll have to revert.

Hi @asturur 
I have the same issue with active selection , can you please tell me that how did you resolve that issue?

**Comment by asturur** [comment]
hi @niketaOptimumnbrew you should open a PR on the 5.x branch that looks like this one, do you think you can?

**Comment by niketaOptimumnbrew** [comment]
> hi @niketaOptimumnbrew you should open a PR on the 5.x branch that looks like this one, do you think you can?

hi @asturur No I don't know how to do.
can you please tell me how to do?

**Comment by asturur** [comment]
i opened one few hours ago with many fixes

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pulls the first one:
https://github.com/fabricjs/fabric.js/pull/9965

**Pull request merged**
