### PR TITLE
fix(geometry): nonTransformedDimensions + `strokeUniform`

### PR DESCRIPTION
**Pull request by goodbot13**
#7605

### CODE REVIEW

**Comment by ShaMan123** [comment]
Could you run `npm run lint -- --fix` and commit the changes (if it makes a giant commit first stash all changes and restore - whitespace OS diffs)
We want to make contributing easier but for now it is what it is.

**Comment by asturur** [comment]
This has been proposed in the past and hasn't been done because it breaks other things.
when we talk of non transformed dimensions, the scale is not taken in consideration. is the size of the object at scale 1. so dividing by scale would bring to strange results. Getting `nonTransformedDimensions` of a rect when it has scale 5 or 1 should give you the same result.

All tests break, and that could be that because they are made to reflect the old behaviour, but i m not confident to accept this change because it fixes a demo.

Does it fix something else?

Let's check it more broadly. SVG import tests could be affected by this for example.

**Comment by ShaMan123** [comment]
I think there's a need to clearly define `strokeUniform`.
I understand it remains the same size no matter the scale.
If so is it part of non transformed dimensions?

**Comment by asturur** [comment]
strokeUniform would mean that the stroke is not affected by the current transformation.
so if you deform a path stretching it on a single axis, the stroke will stay of the same size instead of being larger in some directions.
Is not the feature wrong but our stack of transform to find the size.

**Comment by asturur** [comment]
This behaviour needs to be fixed, just to be clear, there are multiple open issues for it.

**Pull request closed without merging**
