### PR TITLE
add flood fill color

### PR DESCRIPTION
**Pull request by kuafucode**
The flood fill color draws 'background' color or pattern only overlaps with background image instead of the whole canvas like backgroundColor does.
Its very useful when you want to change the color or pattern of the real design area, like a T-shirt background image with transparent background in a canvas.

### CODE REVIEW

**Comment by kangax** [comment]
Could you please make a small demo to see this in action?

**Comment by kuafucode** [comment]
https://jsfiddle.net/74eLgwuw/

**Comment by asturur** [comment]
I would add the function to image.class.js, to have a flood fill color or pattern for images rather than just for canvas background. Then you can use that image for canvas background.

Or the user can still do it using some image layered by and  (rect + image ) using the specific composite operation.

**Comment by kuafucode** [comment]
In our case, flood fill is only an attribute, but not an item in the design, same as background image. Means we don't want to save it as an object with size, position and etc in the output JSON.

**Comment by kuafucode** [comment]
Oh yea, that's a better idea. Would you like to implement it?

**Comment by EddieOne** [comment]
If I draw a circle, can I flood fill it with this?

**Pull request closed without merging**
