### PR TITLE
feat(): `includeDefaultValues` arg

### PR DESCRIPTION
**Pull request by ShaMan123**
Support accepting `includeDefaultValues` as an argument to `toObject` methods instead of fussing with `object.includeDefaultValues`

I have been wanting this for a long time
I think we should drop `includeDefaultValues` as a prop on the object/canvas level
And I think `excludeFromExport` can go away as well if we accept a filter function
```js
toObject(props, includeDefaultValues, filter) {
// for each object
filter(obj) ? 'include': 'exclude'
}
```

### CODE REVIEW

**Comment by asturur** [comment]
Shachar the PR descriptions do not match up the quality and quantity of work you are doing.
To understand what you want to do i need to read the code, and that ( because how my brain works ) makes me distracted with the code instead of the purpose of the code.

I did not ready the code yet, i would like the default behaviour was to not include default values all the time, because that creates enormous object dumps that are often not useful.
It also makes the prototype changes less effective when restoring such object states.

`includeDefaultValues` for me can be either at canvas level, library level, i agree that at object level is not that much useful.
It can also be an argument of the function toObject as you did, that is good too.
I'm ok dumping it as a property.

In general i prefer a single argument in the form of object compared to many arguments, with modern js is easier to handle.

**Comment by ShaMan123** [comment]
@asturur I think `includeDefaultValues` should be false as default as well. It's very strange to put default as true.
How to move forward? Shall we dump this property? I think it's entirely redundant now because once you call `toObject` you simply pass `true` as follows `toObject(undefined, true)`
Sorry for not explaining, will do next time.

**Comment by ShaMan123** [comment]
> In general i prefer a single argument in the form of object compared to many arguments, with modern js is easier to handle.

You mean `toObject({ includeDefaultValues: true, propertiesToInclude: ['stroke'] })`, that's good

**Comment by asturur** [comment]
> > In general i prefer a single argument in the form of object compared to many arguments, with modern js is easier to handle.
> 
> You mean `toObject({ includeDefaultValues: true, propertiesToInclude: ['stroke'] })`? That's good

Yes but when we have es6/TS we can think of change this shape.

**Comment by asturur** [comment]
For me you can move forward.
let's keep the separated arguments, get rid of the property everywhere, and let's have it as a false as default.
That will also avoid to need to check if is boolean or undefined.

**Comment by ShaMan123** [comment]
@asturur what type of object is this?
https://github.com/fabricjs/fabric.js/blob/fd1b0c33f36420f343a5e917a64763a7c7b4c323/src/filters/blendimage_filter.class.js#L225

I am trying to figure out if to pass down the serialization args to it as well

**Comment by ShaMan123** [comment]
Finally all tests are passing. It was horrible...

**Comment by ShaMan123** [comment]
Will die out if/once removeDefaultValues is gone

**Pull request closed without merging**
