### PR TITLE
ci(): restore `package-lock.json` after regression

### PR DESCRIPTION
**Pull request by ShaMan123**
## Motivation

#8777 regression 

## Description

@asturur what version of node/npm are you using? Mine warned me about the lock file and regenerated it
I bet that is the reason for #8778

### CODE REVIEW

**Comment by ShaMan123** [comment]
image

**Comment by asturur** [comment]
so node14 wasn't working anymore because after the sandbox pr they package-lock was too new and was breaking the npm version that comes by default node14.
So i installed node14 npm 6 and generate a node14 package-lock.json to have the pipeline pass.

**Comment by ShaMan123** [comment]
My system complains and won't let me use v1

**Comment by asturur** [comment]
yes mine tries to update it all the time. i think this fix is exactly ok as any other. But before wasn't an issue. i was supposed to look at how we broke it before merging and i forgot.

**Comment by asturur** [comment]
ok so the reason is that when you updated the ci sandbox you moved the package lock from version 2 to version 3.
Probably we can just have version 2 till node14 is around since node14 is supported, and then when we deprecate node 14 we can move to version 3.
Otherwise all ( few node14 users will have to use this flag now to make it work ).

**Comment by asturur** [comment]
Probably you recently moved to node18?

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/8781 here it is

**Pull request closed without merging**
