### PR TITLE
fix(Canvas): flipped viewport transform coords

### PR DESCRIPTION
**Pull request by ShaMan123**
### Motivation
#7471 

### gist
When flipped (negative scale) `Object.isOnScreen` breaks because it tried to check if a point is within `vptCoords` which always returned `false` because when flipped `tl` was greater than `br`.

### Important
I've adjusted tests. 
I need you to review that they are good enough, viewport transform is confusing.
The test enhancement exposed another bug with `isPartiallyOnScreen`.
It's test used stale canvas state, that is why it passed. Now it fails.
The reason it fails is because the rect has a common line with canvas vpt so the intersection test running in `isPartiallyOnScreen` returns true. But it is wrong. `isPartiallyOnScreen` should return false in this case, which is unhandled.

### CODE REVIEW

**Comment by asturur** [comment]
Didn't we fix this already?

**Comment by asturur** [comment]
@ShaMan123 if you have time to move this PR in a branch i can look into test failures and finish it.

**Comment by ShaMan123** [comment]
> @ShaMan123 if you have time to move this PR in a branch i can look into test failures and finish it.

@asturur ?

**Review by asturur — DISMISSED** [review]

**Comment by ShaMan123** [comment]
Should we rebase? Update from master? I'll leave it to you.
I haven't visited this PR in a long time

**Comment by ShaMan123** [comment]
Cause I'm afraid of unwanted overwrite

**Review by asturur — APPROVED** [review]

**Comment by asturur** [comment]
one test needed to be updated, since it had a flipped viewport, and so the new function was supposed to change the test result.
The other i don't know but was effectively an edge case, so i just made less edgy.

**Pull request merged**
