### PR TITLE
Layout constants

### PR DESCRIPTION
**Pull request by asturur**
Swapping constants on layout-manager

### CODE REVIEW

**Review by ShaMan123 — CHANGES_REQUESTED** [review]
Why not doing
```
isImperative(context)
isInitialization(context)
```

clear and saves more

**Comment by asturur** [comment]
i thought about it but i wanted to keep the code as it is it doesn't matter.
What it matters is to do not repeat the same constants around all the time. Function or constant doesn't change much to me

**Comment by ShaMan123** [comment]
I prefer an enum instead.
Any objections?

**Comment by asturur** [comment]
Actually
 ill show you my ideal enum at this point.

**Comment by asturur** [comment]
i ll reopen the PR

**Pull request closed without merging**
