### PR TITLE
simplify code contributions by fully automating the dev setup with Gitpod

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! 

We are currently on a mission to simplify contributors onboarding by fully automating the dev setups for OSS projects with Gitpod(a free online VS Code-like IDE).

In the case of this project, with a single click Gitpod will launch a workspace and automatically:

- clone the `fabric-js` repo.
- install the dependencies.

this is how it looks:

image

You can give it a try on my fork of the repo via the following link:

https://github.com/nisarhassan12/fabric.js

A lot of popular OSS projects out there are already using Gitpod some of them are:

- https://github.com/freeCodeCamp/freeCodeCamp
- https://github.com/facebook/docusaurus
- https://github.com/mozilla/pdf.js 
- https://github.com/photonstorm/phaser/

You can find a brief list of them at https://contribute.dev

image

### CODE REVIEW

**Comment by asturur** [comment]
Seems fine enough to test it.
One question.
Apart a free value, does it offer subscription based features or it is ad supported?

**Comment by nisarhassan12** [comment]
> Seems fine enough to test it.
> One question.
> Apart a free value, does it offer subscription based features or it is ad supported?

Thanks @asturur It is not ad-supported and it does offer some subscription-based features i.e using it with private repos and multiple parallel workspaces and so on.

Gitpod is actually 100% free for Open Source. It can be used by anyone, on any public repository, for up to 50 hours every month. 

Note that we also sponsor professional Open Source developers with unlimited monthly hours, and the majority of Gitpod's code is itself open source.

**Comment by asturur** [comment]
i asked because if i m putting a link in the readme i want to know to what i m sending people to.

**Comment by nisarhassan12** [comment]
Thanks! @asturur Sorry! The link in https://github.com/fabricjs/fabric.js/pull/6308#issue-411833834 was pointing to the wrong repo. I have edited it to:

https://github.com/nisarhassan12/fabric.js

**Comment by nisarhassan12** [comment]
Also, would you like the project to be listed on https://contribute.dev?

**Comment by asturur** [comment]
That is fine by me!

**Comment by asturur** [comment]
Would it work out of the box for fabricjs.com repo?

**Comment by nisarhassan12** [comment]
The `.gitpod.yml` config is essential it is where you tell Gitpod what to do when the workspace starts which could be anything like installing dependencies, building your project, running tests or a web server in watch mode and so on.

For this repo, the config is quite simple:

```yml
tasks:
  - init: npm install
```

but it could be anything. Gitpod is a full-featured cloud IDE where you get Linux in your browser. 


In `gitpod.yml` you can also specify what VS Code extensions you want to have installed for your project.

**Comment by nisarhassan12** [comment]
Please let me know if you need any kind of help in Gitpodifying `fabricjs.com` repo I would love to help.

**Comment by asturur** [comment]
question, can i serve the port 4000 from there and browse it back? that would be extra cool.

**Comment by nisarhassan12** [comment]
Yeah! you can do that in Gitpod when you run a task in a terminal that opens some sort of webserver. You will get a prompt and from there you can click open "Open Preview" or choose "Open Browser" that will open a browser tab:

image

Also, you can automate either to open a browser tab or a preview inside of the editor by specifying in the config.

your gitpod.yml can look something like this:

```yml
tasks:
  - init: npm install # install the dependencies i.e npm install or bundle install and so on
    command: npm start # command to start the webserver
ports:
   - port: 4000
     onOpen: open-preview # will open the preview on the side it can be "open-browser" as well.
```

This is what the open-preview option does:

image

**Comment by nisarhassan12** [comment]
I have made a Pr for adding this project to contribute.dev this is how it looks:

image

I have not found the logo for the project so I have taken a screenshot and added that instead. Is there any logo for the project? Thanks

**Comment by asturur** [comment]
fabriclogo6

this is the one i used to print out stickers and i put on the organization as avatar.
Is the thing nearest to a log i have.

**Comment by nisarhassan12** [comment]
Thanks :slightly_smiling_face:

**Pull request merged**
