### PR TITLE
Various spelling/grammar corrections

### PR DESCRIPTION
**Pull request by melchiar**
First PR so let me know if I'm missing anything. 

Fixed spelling in `_finalizeDimensions` method along with various corrections within documentation. Still not too sure of the meaning of line 297 "the box is intented as aligned to axis of canvas." but corrected to "intended"

Similarly, the meaning of line 510 is unclear: "return transform Matrix for object and not go upward with parents"

### CODE REVIEW

**Comment by asturur** [comment]
Line 510 means that the transform matrix calculated is the one of the object, and not the stacked effect of containers in which the object may be.

Thanks for the fixes, if you manage to rephrase line 510 even better.

**Comment by melchiar** [comment]
Hmm, so I'm still getting the hang of versioning with github and I'm not sure why my commit from #5558 is referenced above (I guess I should get in the habit of separating unrelated things into different branches)

**Comment by asturur** [comment]
it tells me 'unknown repository' otherwise i could give an help.

a branche per feature is like mandatory. Or everything stacks.

**Comment by melchiar** [comment]
Yeah, I had previously committed from master but have since deleted and reforked the repository in order to branch things properly moving forward. Would it be better to just delete this PR and do a new one?

**Comment by asturur** [comment]
yes easier. thanks for your efforts

**Pull request closed without merging**
