### PR TITLE
fix(): `_initRetinaScaling`  initializaing the scaling regardless of settings in Canvas.

### PR DESCRIPTION
**Pull request by ShaMan123**
## Description

fixes the regression from #8510 
I decided to open this PR to have a pure scope for this fix cause I guess that is what you want, instead of fixing as part of #8520 

Decide if you want to close this and merge #8520 or merge this and then that. Anyways if you do the second when dealing with conflict #8520 should win.

## Changes

now `_initRetinaScaling` should be called only if `isRetinaScaling` (doesn't check in the method as previously did)

### CODE REVIEW

**Comment by asturur** [comment]
How the regression was created do we know? the fix you propose seems unrelated to the changes that happend in that pr.
What is the regression actually?

**Comment by ShaMan123** [comment]
If you look at the override of `_initRetinaScaling` you can see it doesn't check if `_isRetinaScaling` though it should, as does the super method in static canvas.
https://github.com/fabricjs/fabric.js/pull/8510/files#r1062365124
https://github.com/fabricjs/fabric.js/pull/8510/files#r1062366689

**Comment by ShaMan123** [comment]
the most simple fix should be 
```
this._isRetinaScaling() && this.__initRetinaScaling(this.upperCanvasEl, this.contextTop); 
```

But it makes more sense to check outside of a method named initRetinaScaling

**Comment by asturur** [comment]
ok now i understand.
That message should have be on the description.

Regarding what makes more sense is usually the smaller change visually.
Imagine if you added the check inside the subclass in the canvas file, that would have explained the issue too.
While with those changes the question was, why are we moving a check from inside out and how that fixes anything.

**Review by asturur — DISMISSED** [review]

**Review by asturur — APPROVED** [review]

**Pull request merged**
