### PR TITLE
feature(controls): get back of lockUniscaling for objects

### PR DESCRIPTION
**Pull request by andrewzolotukhin**
Hi @asturur , I've ressurected lockUniScaling. Could you please review this draft?

### CODE REVIEW

**Comment by asturur** [comment]
i forgot what lockUniscaling was supposed to do, that is why i need time to understand what we want to do.

**Comment by andrewzolotukhin** [comment]
Sure, when you remember just please take a look at this PR it looks like it's the single thing we should add

**Comment by adamgamble** [comment]
This relates to https://github.com/fabricjs/fabric.js/issues/6555

**Comment by asturur** [comment]
I'm sorry @andrewzolotukhin  took me a while to get back here to fabricjs.
I went to check up what uniscaling was doing in 3.x, and basically, it was hiding  the medium side controls.
Was also blocking scaling in other ways but the main point was disable medium side controls and the important function was saved in the design JSON.

I do not want to bring back this functionality as it was i want to search a way to enable it with the new control API.

One example is different control set per object class.
You can have images and text for example to have unilockScaling in this way

```js
const lockedControlSet = {
   ...fabric.Object.prototype.controls;
}
// remove the 4 medium side conrtols
delete lockedControlSet.mr;
delete lockedControlSet.ml;
delete lockedControlSet.mt;
delete lockedControlSet.mb;

// apply this control set to images and text

fabric.Image.prototype.controls = lockedControlSet;
fabric.Text.prototype.controls = lockedControlSet;
```

This is an example.
Are you looking for something completely different?

**Comment by andrewzolotukhin** [comment]
Hi @asturur !

Thank you for your reply. Does that getting serialized to JSON? I understand that I could just path different controls set to some object types. But the problem is that user could disable uniscale locking for particular object from UI and he should still have it disabled once he saved/reloaded project from JSON. 

As I understand, controls state is not being saved to JSON.

**Comment by asturur** [comment]
If the User has to disable per object of the same class, and we want to support it, your solution is the only one that works.

Give me some thinkering time, i really wanted to remove some extra feature that would interact with the others somehow.

In case we need to give it a different name, something like `hideSomethingControls` since it is what it is doing, and we need to add back the property in the object with the default false, where it was, with a description.

```js
    /**
     * When `true`, object non-uniform scaling is locked
     * @type Boolean
     * @default
     */
    lockUniScaling:           false,
```

Just we need better name and better description

**Comment by asturur** [comment]
An alternative is extending the control api to custom getVisibility too.
The issue i have with this approach is that then we have a priority fight between 4 controls hide by a boolean and a specific control enabled manually. Who should win? those are the kind of questions i would like to not have to do.

**Comment by andrewzolotukhin** [comment]
Hi @asturur , would you like me to update a PR with a better naming?

**Comment by asturur** [comment]
Hey sorry for taking so much time here. I got your email, i do not want to bring back lockUniscaling in the official codebase. The controlApi is built to solve those kinds of problems here.

you can write a simple function in this way:

```js

var originalGetVisibility = fabric.Control.prototype.getVisibility;
var getVisibilityForLockUniScaling = function(fabricObject, controlKey) {
  if (this.lockUniScaling) {
    return false;
  }
  return originalGetVisibility(fabricObject, controlKey);
}

// add this function on your controls of choice:
fabric.Object.prototype.controls.tl.getVisibility = getVisibilityForLockUniScaling;
fabric.Object.prototype.controls.tr.getVisibility = getVisibilityForLockUniScaling;
fabric.Object.prototype.controls.bl.getVisibility = getVisibilityForLockUniScaling;
fabric.Object.prototype.controls.br.getVisibility = getVisibilityForLockUniScaling;
```

This is completely in the api idea and you are literally just adding the IF condition you need in the controls you need.

**Comment by andrewzolotukhin** [comment]
Hi @asturur , thanks, your suggestion is working for me. I've just added this field to JSON and used the code you provided. Closing this PR.

**Comment by r043v** [comment]
a bit of trouble as i would easily assume than i could filter object type using this method, ie _fabric.IText.prototype.controls.ml.getVisibility = returnFalseFn;_ but yet do it will in fact set it globally like in your exemple with fabric.Object

so for now i use a system like this :

```
const visibilityRules = {
	'i-text':{
		ml:false, mr:false, mt:false, mb:true, mtr:false
	},
	circle:{
		mtr:false
	}
};

fabric.Control.prototype.originalGetVisibility = fabric.Control.prototype.getVisibility;
fabric.Control.prototype.getVisibility = function( obj, border ){
	if( ( v = visibilityRules[ obj.type ] ) !== undefined )
		if( ( v = v[ border ] ) !== undefined )
			return v ;
	return fabric.Control.prototype.originalGetVisibility.call( this, obj, border );
}
```

**Comment by r043v** [comment]
right, it work fine !

now i could have custom function or enable my own rebind only where it need :)

thanks a lot!

```
const visibilityRules = {
	'i-text':{
		ml:false, mr:false, mt:false, mb:true, mtr:false
	},
	circle:{
		mtr:false
	}
};

const customControl = Object.assign( {}, fabric.Control );
Object.setPrototypeOf( customControl, fabric.Control );

customControl.prototype.originalGetVisibility = customControl.prototype.getVisibility ;
customControl.prototype.getVisibility = function( obj, border ){
	if( ( v = visibilityRules[ obj.type ] ) !== undefined )
		if( ( v = v[ border ] ) !== undefined )
			return v ;

	return customControl.prototype.originalGetVisibility.call( this, obj, border );
}

fabric.IText.prototype.Control = customControl ;
fabric.Circle.prototype.Control = customControl ;

```

**Pull request closed without merging**
