### PR TITLE
MAJOR feat(): Reuse fabric.Point logic for scaling and naming consistency

### PR DESCRIPTION
**Pull request by ShaMan123**

### CODE REVIEW

**Comment by asturur** [comment]
This is good for me!
Where do we can start take note of breaking changes?

**Comment by ShaMan123** [comment]
The CHANELOG?

**Comment by ShaMan123** [comment]
I can draft one in a single PR after we merge these

**Comment by ShaMan123** [comment]
npm bot

I see the action exists

**Review by asturur — APPROVED** [review]
remember to remove the error throw from here too and then merge it if you want

**Comment by asturur** [comment]
there is a npm command now that helps a bit with the changelog.

Should we prepare the breaking changes v6 instructions on fabricjs.com while we make them and we are fresh? we can put the post public right away, is not a secret.

**Comment by ShaMan123** [comment]
Good idea

**Comment by ShaMan123** [comment]
It won't let me merge now because I've updated from master

**Review by asturur — APPROVED** [review]

**Comment by ShaMan123** [comment]
so in order to merge I simply run an update from master and then merge?
you said something about rebasing? Explain please

**Comment by ShaMan123** [comment]
@asturur look https://github.com/fabricjs/fabric.js/runs/5264461632?check_suite_focus=true

**Pull request merged**
