### PR TITLE
fix(fabric.Group) make addWithUpdate compatible with nested groups

### LINKED ISSUE #6738: Add object to nested group
Hi, I use fabric's group recently, I understand when you want to add object to group and update it, you can use addWithUpdate, it works great when when the group is just under canvas.
like that: canvas->group        works

 but when the group(group1) is under another group, it doesn't work anymore, group and it's object's position will be wrong after use addWithUpdate
canvas->group->group1        does not work

check it here
https://jsfiddle.net/zhongjian2008/0re3hjyp/16/

Now i find a workaround it before add object to group in other group, ungroup it first, then group them back. but when there is many group, in deep structure, it makes things complex.

This issue is relate use ActiveSelection to group multi objects that already under a group or deep group. 
canvas->group->group01(node1, node2)
            ->group1->group02(node3, node4)            
var sel = new fabric.ActiveSelection([node1, node3]);     // does not work
canvas.setActiveObject(sel);
canvas.requestRenderAll();

Is there any other solution?  thanks a lot.

### PR DESCRIPTION
**Pull request by asturur**
The pr does not work great yet, needs some understanding of what is not going right.

close #6738

### CODE REVIEW

**Comment by asturur** [comment]
What is the issue so far:
Given the group in the example below, that is created with this code:
```js

var rect = new fabric.Rect({fill: '#0c0', left: 0, top: 0, width: 30, height: 40});
var rect1 = new fabric.Rect({fill: '#c00', left: 30, top: 0, width: 60, height: 50});
window.group0 = new fabric.Group([rect, rect1], {left: 20, top: 30, originX: 'left', originY: 'top'});

var rect2 = new fabric.Rect({fill: '#ccc', left:40, top: 4, width: 30, height: 40});
var rect3 = new fabric.Rect({fill: '#00c', left: 80, top: 7, width: 60, height: 50});
window.group1 = new fabric.Group([rect2, rect3], {left: 40, top: 0, originX: 'left', originY: 'top'});


window.group = new fabric.Group([group0, group1], {left: 0, top: 30, originX: 'left', originY: 'top'});


canvas.add(group);
```
Two triangles are added as a refence of position on the canvas

image

We try to add the text to the grey/blue group. with the code:
```js
window.group1.addWithUpdate(canvas.getActiveObject())
canvas.renderAll()
```

we obtain this:
image

objects are grouped, but everything moved from its position.

**Comment by asturur** [comment]
if i overlap a copy of the group over the new one
image

Seems like the text has been added in correct position and what failed is the outer addWithUpdate

**Comment by asturur** [comment]
@jameszhong2008 seems we have a solution!

**Comment by jameszhong2008** [comment]
Great, hope this PR can be merged soon.

**Review by jameszhong2008 — DISMISSED** [review]
Hope this will be approve soon by reviewer who have write access

**Comment by asturur** [comment]
the pipeline from travis is stopped because we do not have credits anymore. Without pipeline i won't merge anything.
I either need them to approve us as open source project or find another ci/cd application

**Comment by asturur** [comment]
bad bot.

**Pull request merged**
