### PR TITLE
Fix Circle toSVG method adding an incorrect double quote

### PR DESCRIPTION
**Pull request by nmorel**
I also wonder if the condition `if (angle === 0)` should be changed.  
I encountered the double quote even though my circle was "full".  
The calculated angle was `1.4210854715202004e-14`.  
The condition could be something like `if (angle < 0.001 && angle > -0.001)` ?

### CODE REVIEW

**Comment by asturur** [comment]
Can you open a different issue for the angle? we should try to make the angle be calculated as 0 and figure out where the approximation error come from

**Comment by asturur** [comment]
Also since we do not have tests for this case, otherwise it would have fail, would you add one?

**Comment by asturur** [comment]
Perfect!

**Comment by asturur** [comment]
oh there is some linting issue.
Can you try to run `npm run lint_tests` and see the output?

**Comment by nmorel** [comment]
Looking at Travis, it seems the issue is in master branch, on your last commit

**Comment by asturur** [comment]
fixed lint on master, rebuilding this and if is green, merging.

**Pull request merged**
