### PR TITLE
Fix: CircleControls transparentCorners styling

### PR DESCRIPTION
**Pull request by Kronoxis**
CircleControls didn't listen to the `transparentCorners` styling of the fabricObject. 

## Steps to reproduce
You can verify this issue in the controls customization demo: http://fabricjs.com/controls-customization
1. Set `cornerStyle` to option 2 (circular)
2. Toggle `transparentCorners` on

### CODE REVIEW

**Comment by asturur** [comment]
Hi, thanks for the PR.
One visual test around circle coners is indeed failing, and this is expected.

Could you please have a look at why is failing and fix it?

Do you know how to run the test suite locally?

**Comment by Kronoxis** [comment]
> Could you please have a look at why is failing and fix it?

I'm assuming the test image `controls4.png` is wrong, as this has solid circle controls while transparent are used in the test code. How do I go about re-rendering this image so I can provide the repo with the correct test image?

> Do you know how to run the test suite locally?

I'm not familiar with writing and running tests in JavaScript, could you guide me through how I can do this? So far I have cloned the repo on my machine and installed the npm dependencies.

**Comment by asturur** [comment]
if you are past `npm install`, you should be able to do the following:

`npm run build:fast` will build fabric.js with your fix
`npm run test:visual` will run the tests and give you a single failure
once you are sure that the old image was wrong and now with the new code needs an updated, you can search it and delete the image.
run again the tests with `npm run test:visual` and the test won't find the image and create it.
before committing the changes, you should remove the built dist file with `git checkout master dist`
then the usual `git add .` and `git commit -am 'corrected the snapshot'` and you should be done.

**Comment by Kronoxis** [comment]
I have uploaded the new `controls4.png` image and the visual unit test succeeds now.

**Review by asturur — APPROVED** [review]

**Comment by asturur** [comment]
Thanks!

**Pull request merged**
