### PR TITLE
chore(TS): migrate Eraser

### PR DESCRIPTION
**Pull request by ShaMan123**
## Description

Migrate eraser and refactor to a module.
Adapt fabric entities so there is no mutation done (the mixin used to mutate the prototypes of Object, Group, Canvas)
Can be regarded as Eraser v3, see v2 #7470 for reference

## Changes

- comply EraserBrush to brush pattern
- perf(): doesn't need to do a full redraw of path each frame/step
- perf(): optimize `needsFullRender` - move alpha checking to PencilBrush and descendants not including eraser (I think we should try masking PencilBrush, same as the eraser does, but with `fillRect` of `color`, that will make redrawing the entire path redundant in case of opacity, am I right?)
- perf(PencilBrush): fixed straight line used to redraw until mouse up regardless of the straight line state
- fix(): erasing + straight line
- feat(): alpha erasing
- fix(): clipPath, changed rendering logic so that first the brush draws over top context, then it is masked and then it is used to clip the main context. Makes #7991 #7984 obsolete and `won't fix` and enhances perf
- feat(): `updating`, eraser will subscribe to canvas rendering and update its pattern 
- fix(): utilize `renderCanvas` to render pattern correctly (was missing out canvas#clipPath)

## Gist

- [ ] first merge #8476 https://github.com/fabricjs/fabric.js/compare/clip-brush...ts-eraser
- [x] add tests
   - [ ] no idea why `top_ctx` goldens are wrong... missing the opaic red rect that is visible when actually erasing
(actual) freedrawing_eraser_custom_stack_alpha_clipped_top_ctx
- [ ] toSVG tests
- [ ] opaic background destroys the eraser pattern... no idea why

## In Action

[Edit fabric-nextjs-sandbox (forked)](https://codesandbox.io/s/fabric-nextjs-sandbox-forked-njtsgy?fontsize=14&hidenavigation=1&module=%2Fpages%2Findex.tsx&theme=dark)

https://user-images.githubusercontent.com/34343793/206911085-06bad37d-801f-4cc6-8583-1c17ba6ac220.mp4

**With clip path**

https://user-images.githubusercontent.com/34343793/206911099-af39d7b9-3005-45d3-b061-5b32eff218da.mp4

### CODE REVIEW

**Comment by ShaMan123** [comment]
stable

**Comment by ShaMan123** [comment]
This is a major step forward!

**Comment by kyun** [comment]
@ShaMan123  Is this PR still working?

**Comment by ShaMan123** [comment]
We need to merge it
Not sure when

**Comment by clphan** [comment]
Hi @ShaMan123, may we know this pr still on progress? do you know when it will be merged 🙇

**Comment by ShaMan123** [comment]
I do not know
But it should
It is good to go, just needs to update from master

**Comment by JeremyMees** [comment]
@ShaMan123
Do you have an idea when this is going to be added? I really don't wont to downgrade to version 5 😬 
I hope this get's added soon because i really need it.

**Comment by ShaMan123** [comment]
@asturur

**Comment by ShaMan123** [comment]
I see this needs porting.
The diff is in a bad state

**Comment by ShaMan123** [comment]
closing in favor of https://github.com/ShaMan123/erase2d

**Pull request closed without merging**
