### PR TITLE
fix(geometry): bbox of clipped object

### PR DESCRIPTION
**Pull request by ShaMan123**
Motivation #5275 #7473 

What should happen when an object is clipped?
Should it be bound to the clipped area?
If the clip path isn't centered what then?
Should originX/Y be relative to the clip path center?

Test
https://codesandbox.io/s/wpu1g

### CODE REVIEW

**Comment by asturur** [comment]
the issue here is that:
- clipPath can be larger than the object
- clipPath can be scaled independently of the object and break calculations
- clipPath can be positioned in a super weird way so that its dimensions combined with left/top of the object would be mess up.

I wonder if a possible solution is to separate the code that renders controls/bounding box from the code that is used for rendering and calculations of other kinds.
I think this _getTransformedDimension is shared between the 2.

**Comment by ShaMan123** [comment]
It seems that [`drawBorders`](https://github.com/fabricjs/fabric.js/blob/8ecbdb10f797ce07fb4dccca348fe63ff1558b62/src/mixins/object_interactivity.mixin.js#L124) relies on [`_calculateCurrentDimensions`](https://github.com/fabricjs/fabric.js/blob/8ecbdb10f797ce07fb4dccca348fe63ff1558b62/src/mixins/object_geometry.mixin.js#L707)
`drawControls` relies on `oCoords` that in turn relies on `_calculateCurrentDimensions`.
So it seems `_calculateCurrentDimensions` is used by all of them.

**Comment by ShaMan123** [comment]
In think this PR is a great example that demonstrates the need of a coherent object API.
This way with a simple override of getDimensions or what ever I can handle special cases myself.

**Comment by ShaMan123** [comment]
This can die out because of group's layout engine

**Pull request closed without merging**
