### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jeroenrosendaal**
Updated "Devleoping" to "Developing"

### CODE REVIEW

**Comment by ShaMan123** [comment]
thanks

**Comment by ShaMan123** [comment]
@jeroenrosendaal the guide has been rewritten. After reading it, do you any comments? something needs more refining?

**Review by ShaMan123 — APPROVED** [review]

**Comment by jeroenrosendaal** [comment]
@ShaMan123 I think the ```Developing```  section is a bit confusing if you never used ```codesandbox``` before. I tried using it but dit not succeed. I also tried building the project manually but came across some errors regarding the conversion to typescript files. Seems like the references inside the ```build.js``` file are not updated yet.

**Comment by ShaMan123** [comment]
1. `build.js` is deprecated - we switched to a new build system
2. codesandbox is not directly related the the developing sectin. Please elaborate

**Comment by jeroenrosendaal** [comment]
@ShaMan123 What kind of build system do you use currently? I would like to test and contribute to the code. I've had some experience with the build.js. I assumed that codesandbox was the 'new way'.

**Comment by ShaMan123** [comment]
we moved to `rollup`
the guide covers how to use the commands
`npm run build` etc.

**Comment by jeroenrosendaal** [comment]
What guide are you referencing to?
I followed https://github.com/fabricjs/fabric.js#building section.
But ```npm run build``` did indeed the trick.

**Comment by ShaMan123** [comment]
Ahh I see
That is on it's way out #8189

**Comment by ShaMan123** [comment]
look here [README](https://github.com/fabricjs/fabric.js/blob/f36642a19743ffee1d01309edcaaa41221fa5184/README.md)

**Comment by jeroenrosendaal** [comment]
Thanks!

**Pull request merged**
