### PR TITLE
Word boundary search update

### PR DESCRIPTION
**Pull request by durga598**
Update to check in grapheme text rather to normal text

### CODE REVIEW

**Comment by asturur** [comment]
can you help me figure out what is broken and how we are fixing it? what kind of text was failing the word search?

**Comment by durga598** [comment]
Check this [jsfiddle](https://jsfiddle.net/durga598/b0n52e9c/show)

**Comment by asturur** [comment]
Ok seems good to me.
I do not understand this language ( hindi? ) and i do not now what is the expected user effect.

Take this grapheme cluster:
image

It has 2 cursor positions, one at the start and one at the middle, if you  press space, it moves as a single block.
I think this is a fabricJs error, or the grapheme splitter you use is not working as expected?

**Comment by durga598** [comment]
Yes it is Hindi, and most of Indian language works like that way. In google doc/notepad I tried, it works like you have mentioned. It removes one piece at a time, as the complex letter comprised of three letters.
letters
And while moving cursor it takes as single letter
text
But using fabricjs, it takes another step in between, is it because of grapheme splitter?
fabric text

**Comment by asturur** [comment]
probably because of the grapheme splitter used that is consodering it 2 pieces ( you can inspect the _text array i suppose

**Comment by asturur** [comment]
going to merge this, should not break anything

**Pull request merged**
