### PR TITLE
fix: toJSON function param

### PR DESCRIPTION
**Pull request by xiaoxintang**
## Motivation
fix toJSON function bug

## Description
`toJSON` is call `toObject` & it's doc show we can have an array param but actually not

## Changes
add optional param like `toObject` do

### CODE REVIEW

**Comment by asturur** [comment]
Sorry this can't be done. You have to use toObject for the extra parameters. To JSON receives already some parameters, i think it receives the key of the object you are serializing ans so we can't put there a different argument.

**Comment by asturur** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior

**Comment by xiaoxintang** [comment]
so,you should delete this doc? @asturur 

image

**Comment by asturur** [comment]
if the bug has been fixed in 5.3.x yes

**Pull request closed without merging**
