### PR TITLE
chore(): no dist

### PR DESCRIPTION
**Pull request by ShaMan123**
## Description

rm dist folder for good

**TODO**
- [ ] verify that npm picks up the dist folder

### CODE REVIEW

**Review by asturur — APPROVED** [review]

**Comment by asturur** [comment]
THis is going to break a bunch of JSfiddle around. I suppose that would happen anyway when release 6.0

**Comment by ShaMan123** [comment]
Will it? Aren't we going to publish npm/cdn versions with a build.
My intention is just to remove it from version control.

**Comment by asturur** [comment]
Yes some fiddle link directly to github.com for the master file, with no version, and that is likely broken anyway.
Was just pointing out, i think we should remove it anyway

**Comment by ShaMan123** [comment]
We should use codesandbox or gitpod or anything that supports a build script
#8135 is the solution for that

**Comment by ShaMan123** [comment]
closed as completed by #8632

**Pull request closed without merging**
