### PR TITLE
InsertChars before adding to canvas throw error #4635

### PR DESCRIPTION
**Pull request by 0ro**
It fix for this issue [#4635](https://github.com/fabricjs/fabric.js/issues/4635)
I've created a [fiddle](https://jsfiddle.net/DenBogdanov/xaLjp87g/1/) that demonastrate the fix.

P.S. This is my first pull request

### CODE REVIEW

**Comment by asturur** [comment]
Hey i think the fix is good.
Do you think we can add a test that demonstrates it is possible to use insertChars without adding the element on a canvas?

I m also a bit unhappy of `this.ctx` in general.
Is a left over of old code that would be best to not have at all.
I think is used for measuring text.

**Comment by asturur** [comment]
Ideally we need a test, and opening an issue to followup of proper removal of this.ctx and then we can merge,

**Comment by 0ro** [comment]
There is not unit test for Textbox yet. Should I create tests for it? What tests should be described there?
And what test environment do you use for 1.7.22. Because when I run `npm run test` I get this output in my console
```
➜  fabric.js git:(textbox-cache-context) ✗ npm run test


> fabric@1.7.22 test /Volumes/MacDATA/Job/fabric.js
> node test.js


Testing  /Volumes/MacDATA/Job/fabric.js/dist/fabric.js ... 
jpeg toDataURL not supported
Error: Process blocked for too long
    at Timeout.<anonymous> (/Volumes/MacDATA/Job/fabric.js/node_modules/qunit/lib/testrunner.js:83:30)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/den/.nvm/versions/node/v6.17.1/bin/node" "/Users/den/.nvm/versions/node/v6.17.1/bin/npm" "run" "test"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! fabric@1.7.22 test: `node test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fabric@1.7.22 test script 'node test.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fabric package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node test.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fabric
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fabric
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/MacDATA/Job/fabric.js/npm-debug.log
```

**Comment by asturur** [comment]
i did not understood this was for 1.7.22, let me check again then.

**Comment by asturur** [comment]
if this is for 1.7 we can merge straight.
No need to make you spend time on increasing test converage of a deprecated branch
1.7 is unsupported, and i suggest you to look at latest master ( pre 3.0 ). There are a few bugs yet but overall is way better.

**Pull request merged**
