### PR TITLE
chore(lint): disallow `Math.hypot`, `window`, `document`

### PR DESCRIPTION
**Pull request by ShaMan123**
I found out how to use [no-restricted-syntax](https://eslint.org/docs/latest/rules/no-restricted-syntax) to match `Math.hypot` and [no-restricted-globals](https://eslint.org/docs/latest/rules/no-restricted-globals) to match `window` and `document`

## Motivation
https://stackoverflow.com/questions/62931950/different-results-of-math-hypot-on-chrome-and-firefox

## In Action

image
image
image
image
image

### CODE REVIEW

**Review by ShaMan123 — COMMENTED** [review]
Why doesn't the lint job detect the error?

**Comment by ShaMan123** [comment]
image

**Review by ShaMan123 — COMMENTED** [review]
The `window` rule will fail as long as there are existing cjs export directives
`})(typeof exports !== 'undefined' ? exports : window);`

**Comment by asturur** [comment]
ok, is fine anyway, even if window fails for now.

**Review by asturur — APPROVED** [review]

**Pull request merged**
