### PR TITLE
types(): assert this state

### PR DESCRIPTION
**Pull request by ShaMan123**
## Motivation
We were looking for a mechanism to instruct TS that we are executing in a given state.
We could use it for cached object etc.

## Description
Unfortunately it is impossible to combine an `asserts` directive with `this is T`. That would have been great.

## Gist

View the following code snippet in the [TS playground](https://www.typescriptlang.org/play?#code/LAKFFMA8AcHsCcAuACRBPa5kEEDOvwkBpcNXAHgBUAaZI5KRcAOwBNdkBrU2AM2UoA+ZAF4ByAGTIASuADGCVuSK0AcrGaqArgBsdAQwBGO8FQDaRALqDBAblAQYCFHIP5kAYVgBbbxoCy4IgAFrDsyADeoMjIAPQAVPHRMfHIWgSowQCWHFnMTPDM+jrI3kGhrKiwyPr4hCi4iPpMyKxa8HkA5gyQ8lqIWRrJyPGxydDwsExyTJW1BEiU2biUGKb0jCzh3Gh8mTmCABQAlABcNXVIHCE5yLd4C4gkZOTD+7jUb0TJwlEgMTFYrFkMxYLBoLRgoQsBodGhkLwEAIAMrJAC+oAxYBArnmyAAYmCekw2BwvL4AuUwhw-jFGs1wAAFSbQAD852YWm8hkI9n+pSprBOkTe8CC7WY7wAdPSmMzwcgANTIACMfJiWJi83quGRTSYwtpAJuuCl2sWy1WmHIAHJZUyWTajsd1QCxYgJdL7fLoErVa6sWigA)

```ts


export type AssertKeys<T, K extends keyof T> = T & Record<K, NonNullable<T[K]>>;

export class CommonMethods {
  /**
   * use this internal method to assert state during execution
   */
  protected assertThisType<K extends keyof this>(): asserts this is AssertKeys<
    this,
    K
  > {
    // noop, here only for TS
  }
}

class Foo extends CommonMethods {
  stateProp?: number;
  method() {
    return this.stateProp + 1;
  }
  assertsState() {
    this.assertThisType<'stateProp'>();
    return this.stateProp + 1;
  }
}
```

<details><summary><b>Output</b></summary>

```ts
export class CommonMethods {
    /**
     * use this internal method to assert state during execution
     */
    assertThisType() {
        // noop, here only for TS
    }
}
class Foo extends CommonMethods {
    method() {
        return this.stateProp + 1;
    }
    assertsState() {
        this.assertThisType();
        return this.stateProp + 1;
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/LAKFFMA8AcHsCcAuACRBPa5kEEDOvwkBpcNXAHgBUAaZI5KRcAOwBNdkBrU2AM2UoA+ZAF4ByAGTIASuADGCVuSK0AcrGaqArgBsdAQwBGO8FQDaRALqDBAblAQYCFHIP5kAYVgBbbxoCy4IgAFrDsyADeoMjIAPQAVPHRMfHIWgSowQCWHFnMTPDM+jrI3kGhrKiwyPr4hCi4iPpMyKxa8HkA5gyQ8lqIWRrJyPGxydDwsExyTJW1BEiU2biUGKb0jCzh3Gh8mTmCABQAlABcNXVIHCE5yLd4C4gkZOTD+7jUb0TJwlEgMTFYrFkMxYLBoLRgoQsBodGhkLwEAIAMrJAC+oAxYBArnmyAAYmCekw2BwvL4AuUwhw-jFGs1wAAFSbQAD852YWm8hkI9n+pSprBOkTe8CC7WY7wAdPSmMzwcgANTIACMfJiWJi83quGRTSYwtpAJuuCl2sWy1WmHIAHJZUyWTajsd1QCxYgJdL7fLoErVa6sWigA)

### CODE REVIEW

**Review by ShaMan123 — COMMENTED** [review]
@asturur  Thoughts?

**Comment by asturur** [comment]
I m not sure i understand how it works or how to use it.
Can you compare with the first argument this

like 
```
drawingFunction(this: TActuallyCachedObject, ...args) {
this.cacheCanvas. <--- this is ok because this is `TActuallyCachedObject`?
}
```

**Comment by ShaMan123** [comment]
Open the provided TS playground I referenced.
You will see `stateProp` in both methods `method` (maybe undefined) and `assertsState` (asserted).
So answering your question it is complementary to typing this. Used in cases that during a method state changes and you want to assert it for TS to stop annoying.
```ts
performDrawing(ctx) {
  !checkCaches() && refreshCaches();
  this.assertThisType<keyof TActuallyCachedObject>();
  this.drawingFunction(ctx); // TS will not complain
}

```

**Comment by ShaMan123** [comment]
A good and simple example are methods in `canvas_events` that call `_cacheTransformEventData` and assert that `this._pointer` for example is now set. Calling `this.assertThisType<'_pointer'>` does the trick.

This is just an internal utility. And more a discussion than a suggestion relevant to previous discussions and TS annoyance.

**Pull request closed without merging**
