### PR TITLE
fix(fabric.Textbox): The same text does not need to be wrapped

### PR DESCRIPTION
**Pull request by proYang**
Hi, I encountered and fixed the problem. 🐛

### CODE REVIEW

**Comment by proYang** [comment]
I have added some test cases that require `npm run build`.

**Comment by asturur** [comment]
can you explain a bit better what the bug was about? can you reproduce it?

**Comment by proYang** [comment]
> can you explain a bit better what the bug was about? can you reproduce it?

I wrote an example.    [https://jsfiddle.net/slaneyang/5pbwon19/](url)

QQ20200928-111211-HD

**Comment by housseynCheriet** [comment]
Best explanation of easing function
https://www.selectionjs.com/animation

**Comment by asturur** [comment]
Ok is a bit more clear now.
if you open a PR please take care that the people maintaining the library can understand where the problem is, and how to trigger it.

**Comment by asturur** [comment]
Something is failing with lint. Did you run `npm run lint_tests`?

**Comment by proYang** [comment]
> Something is failing with lint. Did you run `npm run lint_tests`?

Oh!  Just a moment. I'll fix it.

**Comment by proYang** [comment]
> > Something is failing with lint. Did you run `npm run lint_tests`?
> 
> Oh! Just a moment. I'll fix it.

@asturur  done

**Review by asturur — APPROVED** [review]

**Comment by asturur** [comment]
Thanks!

**Pull request merged**
