### PR TITLE
CD(): website submodule

### PR DESCRIPTION
**Pull request by ShaMan123**
## Motivation

have the website repo visible

## Description

`git submodule add https://github.com/fabricjs/fabricjs.github.io website`

## In Action

image

### CODE REVIEW

**Comment by ShaMan123** [comment]
I wonder if there is a way not to point to a specific commit

**Comment by ShaMan123** [comment]
reading https://stackoverflow.com/questions/8191299/update-a-submodule-to-the-latest-commit seems it must be updated...
we can add an action for that

**Comment by asturur** [comment]
i think it needs to be updated because submodules are meant to be imported as code dependencies?

**Comment by asturur** [comment]
What we do with it, what does it enable?

**Comment by asturur** [comment]
we can have it of course, but we need to write an action to write a commit everytime we want to update it, no thanks.

**Review by asturur — APPROVED** [review]

**Pull request merged**
