### PR TITLE
ci(): Multi chunk build

### PR DESCRIPTION
**Pull request by ShaMan123**
## Description

Rollup config and more to allow dynamic imports if needed.
Leaving this here for reference

### CODE REVIEW

**Comment by asturur** [comment]
This PR reminds me i really want to stop rolling up node. Seems completely unnecessary.
What do you think?
reference: https://github.com/fabricjs/fabric.js/pull/8649/

**Comment by ShaMan123** [comment]
I think you are right.
And as you said in that PR we don't need to bundle es for the browser as well. Only transpile to js.
Then one day the umd build is not needed at all.

**Comment by ShaMan123** [comment]
@asturur what do you think about submodules?

**Comment by ShaMan123** [comment]
controls, brushes, filters are great candidates.
Github has a decent concept for it.

**Comment by ShaMan123** [comment]
And it means we could expose them to npm as standalones so a dev can do something like
```ts
import { Canvas } from '@fabric/web' // '@fabric/node'
import { Control } from '@fabric/controls
import { Text } from '@fabric/Text'
import { Circle } from '@fabric/core'
```

What do you think?
Might be an overkill once we stop bundling.

**Comment by asturur** [comment]
i m not sure we ever stop bundling, bundling is not going away anywhere soon. There are benefits of various kinds even when using http2, apart that it doesn't cost us anything to keep a bundle rolling.

At some point a way to import single files from the node_modules folder will be super common and adopted and we can just jump on that.

Right now offering transpiled single files that import each other + a bundle seems the best we can do.

**Pull request closed without merging**
