### PR TITLE
Adding a safe check for _setImageSmoothing function to make sure that variable is not a null

### PR DESCRIPTION
**Pull request by BishoyBishai**

### CODE REVIEW

**Comment by asturur** [comment]
How did you trigger this bug? fabric in node?

**Comment by BishoyBishai** [comment]
> How did you trigger this bug? fabric in node?

We use fabric in our project and this bug has been trigged by Sentry.

**Comment by asturur** [comment]
what is Sentry?

**Comment by BishoyBishai** [comment]
> what is Sentry?

@asturur [Sentry](https://sentry.io/about/)

**Pull request closed without merging**
