### PR TITLE
ci(): update code coverage action comment

### PR DESCRIPTION
**Pull request by ShaMan123**
No more bot spamming in PRs and emails!

### CODE REVIEW

**Comment by ShaMan123** [comment]
ci posted a comment before this one

**Comment by ShaMan123** [comment]
YES!!! SUCCESSS!

**Review by asturur — APPROVED** [review]

**Comment by asturur** [comment]
for me an update to the original would have been nicer :) now there are 89 forks.

**Comment by ShaMan123** [comment]
You mean for the repo
sure
I opened a pr on the most attractive fork I found
but it seems dead too

**Comment by ShaMan123** [comment]
I wonder if this action will fail as the prev one did on PRs from the community

**Pull request merged**
