### PR TITLE
Add Start and End angle to circle.

### PR DESCRIPTION
**Pull request by asturur**
Add option to circle for start and end angle, to draw an ARC.
in radiants, not in degree to avoid writing a setter and getter that does the conversion.
Internally is better radiants i think.

as per request of issue #1612

I modified the render, the initialize method, toObject and toSvg methods.
Did i forget something?
Bounding box is the original of the circle, i think it makes sense to leave how it is.

Canvas:
image

svg export
image

resulting svg

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="900" height="500" xml:space="preserve"><desc>Created with Fabric.js 1.4.11</desc><defs></defs><path d="M 21.213203435596427 21.213203435596423 A 30 30 0 0 1  -21.213203435596423 21.213203435596427" style="stroke: #00FF00; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #00FF00; fill-rule: source-over; opacity: 1;" transform="translate(445.74 232.61) rotate(51.79) scale(4.21 4.21) "/>
<path d="M -21.213203435596423 -21.213203435596427 A 30 30 0 0 1  21.213203435596427 -21.213203435596423" style="stroke: #FF0000; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #00FF00; fill-rule: source-over; opacity: 1;" transform="translate(305.74 242.61) rotate(51.79) scale(4.21 4.21) "/>
<path d="M -21.213203435596423 21.213203435596427 A 30 30 0 0 1  -21.21320343559643 -21.213203435596423" style="stroke: #0000FF; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #00FF00; fill-rule: source-over; opacity: 1;" transform="translate(439.2 278.3) rotate(51.79) scale(3.86 4.21) matrix(-1 0 0 1 0 0)  "/>
<path d="M 21.213203435596427 -21.213203435596423 A 30 30 0 0 1  21.213203435596427 21.213203435596423" style="stroke: #00FFFF; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #00FF00; fill-rule: source-over; opacity: 1;" transform="translate(291.74 316.61) rotate(51.79) scale(4.21 4.21) matrix(-1 0 0 1 0 0)  "/>
<path d="M 21.213203435596427 21.213203435596423 A 30 30 0 0 1  -21.213203435596423 21.213203435596427" style="stroke: #00FF00; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #00FF00; fill-rule: source-over; opacity: 1;" transform="translate(174.5 130.5) "/>
<path d="M -21.213203435596423 -21.213203435596427 A 30 30 0 0 1  21.213203435596427 -21.213203435596423" style="stroke: #FF0000; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #00FF00; fill-rule: source-over; opacity: 1;" transform="translate(174.5 130.5) "/>
<path d="M -21.213203435596423 21.213203435596427 A 30 30 0 0 1  -21.21320343559643 -21.213203435596423" style="stroke: #0000FF; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #00FF00; fill-rule: source-over; opacity: 1;" transform="translate(174.5 130.5) "/>
<path d="M 21.213203435596427 -21.213203435596423 A 30 30 0 0 1  21.213203435596427 21.213203435596423" style="stroke: #00FFFF; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #00FF00; fill-rule: source-over; opacity: 1;" transform="translate(174.5 130.5) "/>
</svg>
```

### CODE REVIEW

**Comment by evandavey** [comment]
@asturur - what is the logic of keeping the original bounding box and how could this be changed?  I am trying to use the mouse:over event for a semi-circle but it triggers on the half of the circle that is not drawn which is confusing to a user.  As another example,  if I add a semi-circle to the group along with other objects and access group.width in order to calculate the group center point, the undrawn part of the circle is included so the center point is inaccurate.

**Comment by asturur** [comment]
This startAngle and endAngle are not complete.
We should add methods to fix the bounding box indeed.

I think that writing a specific method for get nonTrasnformedDimensions should be enough.
Its a bit of a geometric problem if someone is interested in doing it

**Comment by asturur** [comment]
Also maybe giving an option to include the center point and making a circle sector may be another idea?

**Comment by asturur** [comment]
We have 2 ways to find the bbox, already embedded in fabricJS.
One is to calculate the path and use what we use for paths, the other is to take the points and use what we use for polygon, we should we covered for that, the problem is just doing it in a nice elegant way.

**Comment by asturur** [comment]
i see how including the center in the segment can be usefull to create pie charts without starting from SVGs ( i also imagine that positioning the slices is difficult )

**Comment by evandavey** [comment]
This is a quick (not fully tested) workaround I am using, referencing https://math.stackexchange.com/a/185453

```
fabric.Circle.prototype._getNonTransformedDimensions = function() {
    var start_x = this.left + this.radius*Math.cos(this.startAngle);
    var start_y = this.top + this.radius*Math.sin(this.startAngle);
    var end_x = this.left + this.radius*Math.cos(this.endAngle);
    var end_y = this.top + this.radius*Math.sin(this.endAngle);

    var w = end_x - start_x;
    var h = end_y - start_y

    return { x: w, y: h };
}
```

**Comment by evandavey** [comment]
I implemented a draft algorithm which I think calculates the width and height of the arc correctly, which I use to set the width/height properties. However, the bounding box location (from getBoundingRect()) is not positioned correctly (see image) and the arc no longer triggers a mouseover event.  This arc was drawn with originX = originY = 'center'.

image

**Pull request merged**
